#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 92
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 7

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_let = 2,
  anon_sym_SEMI = 3,
  anon_sym_out = 4,
  anon_sym_COMMA = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_if = 8,
  anon_sym_else = 9,
  anon_sym_while = 10,
  anon_sym_LPAREN = 11,
  anon_sym_RPAREN = 12,
  anon_sym_LT_GT = 13,
  anon_sym_PLUS_LT_GT = 14,
  anon_sym_DASH_LT_GT = 15,
  anon_sym_STAR_LT_GT = 16,
  anon_sym_SLASH_LT_GT = 17,
  anon_sym_STAR_STAR_LT_GT = 18,
  anon_sym_PERCENT_LT_GT = 19,
  anon_sym_BANG_EQ = 20,
  anon_sym_EQ_EQ = 21,
  anon_sym_LT = 22,
  anon_sym_LT_EQ = 23,
  anon_sym_GT_EQ = 24,
  anon_sym_GT = 25,
  anon_sym_PLUS = 26,
  anon_sym_DASH = 27,
  anon_sym_STAR = 28,
  anon_sym_SLASH = 29,
  anon_sym_PERCENT = 30,
  anon_sym_STAR_STAR = 31,
  anon_sym_POUND = 32,
  aux_sym_line_comment_token1 = 33,
  aux_sym_line_comment_token2 = 34,
  aux_sym_line_comment_token3 = 35,
  sym_number_literal = 36,
  sym_string_literal = 37,
  sym_program = 38,
  sym__root_statement = 39,
  sym_let_binding = 40,
  sym_out_statement = 41,
  sym_block = 42,
  sym__items = 43,
  sym_if_expr = 44,
  sym_while_expr = 45,
  sym__lhs_expression = 46,
  sym_parenthesized_expression = 47,
  sym__initializer = 48,
  sym__expression = 49,
  sym_assignment_expression = 50,
  sym_binary_expression = 51,
  sym_primary_expression = 52,
  sym_line_comment = 53,
  sym__literal = 54,
  aux_sym_program_repeat1 = 55,
  aux_sym_out_statement_repeat1 = 56,
  aux_sym_block_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_let] = "let",
  [anon_sym_SEMI] = ";",
  [anon_sym_out] = "out",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT_GT] = "<>",
  [anon_sym_PLUS_LT_GT] = "+<>",
  [anon_sym_DASH_LT_GT] = "-<>",
  [anon_sym_STAR_LT_GT] = "*<>",
  [anon_sym_SLASH_LT_GT] = "/<>",
  [anon_sym_STAR_STAR_LT_GT] = "**<>",
  [anon_sym_PERCENT_LT_GT] = "%<>",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_STAR_STAR] = "**",
  [anon_sym_POUND] = "#",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [aux_sym_line_comment_token2] = "line_comment_token2",
  [aux_sym_line_comment_token3] = "line_comment_token3",
  [sym_number_literal] = "number_literal",
  [sym_string_literal] = "string_literal",
  [sym_program] = "program",
  [sym__root_statement] = "_root_statement",
  [sym_let_binding] = "let_binding",
  [sym_out_statement] = "out_statement",
  [sym_block] = "block",
  [sym__items] = "_items",
  [sym_if_expr] = "if_expr",
  [sym_while_expr] = "while_expr",
  [sym__lhs_expression] = "_lhs_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym__initializer] = "_initializer",
  [sym__expression] = "_expression",
  [sym_assignment_expression] = "assignment_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_primary_expression] = "primary_expression",
  [sym_line_comment] = "line_comment",
  [sym__literal] = "_literal",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_out_statement_repeat1] = "out_statement_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_out] = anon_sym_out,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT_GT] = anon_sym_LT_GT,
  [anon_sym_PLUS_LT_GT] = anon_sym_PLUS_LT_GT,
  [anon_sym_DASH_LT_GT] = anon_sym_DASH_LT_GT,
  [anon_sym_STAR_LT_GT] = anon_sym_STAR_LT_GT,
  [anon_sym_SLASH_LT_GT] = anon_sym_SLASH_LT_GT,
  [anon_sym_STAR_STAR_LT_GT] = anon_sym_STAR_STAR_LT_GT,
  [anon_sym_PERCENT_LT_GT] = anon_sym_PERCENT_LT_GT,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_STAR_STAR] = anon_sym_STAR_STAR,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [aux_sym_line_comment_token2] = aux_sym_line_comment_token2,
  [aux_sym_line_comment_token3] = aux_sym_line_comment_token3,
  [sym_number_literal] = sym_number_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_program] = sym_program,
  [sym__root_statement] = sym__root_statement,
  [sym_let_binding] = sym_let_binding,
  [sym_out_statement] = sym_out_statement,
  [sym_block] = sym_block,
  [sym__items] = sym__items,
  [sym_if_expr] = sym_if_expr,
  [sym_while_expr] = sym_while_expr,
  [sym__lhs_expression] = sym__lhs_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym__initializer] = sym__initializer,
  [sym__expression] = sym__expression,
  [sym_assignment_expression] = sym_assignment_expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_primary_expression] = sym_primary_expression,
  [sym_line_comment] = sym_line_comment,
  [sym__literal] = sym__literal,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_out_statement_repeat1] = aux_sym_out_statement_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_out] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_LT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_comment_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym__root_statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_out_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__items] = {
    .visible = false,
    .named = true,
  },
  [sym_if_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_while_expr] = {
    .visible = true,
    .named = true,
  },
  [sym__lhs_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__initializer] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_assignment_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_primary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_out_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_condition = 1,
  field_format_str = 2,
  field_left = 3,
  field_name = 4,
  field_operator = 5,
  field_right = 6,
  field_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_format_str] = "format_str",
  [field_left] = "left",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 2},
  [6] = {.index = 7, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_format_str, 1},
  [1] =
    {field_condition, 1},
  [2] =
    {field_value, 1},
  [3] =
    {field_name, 1},
    {field_value, 2, .inherited = true},
  [5] =
    {field_left, 0},
    {field_right, 2},
  [7] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 15,
  [19] = 16,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 22,
  [26] = 23,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 31,
  [33] = 33,
  [34] = 33,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 41,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 44,
  [61] = 45,
  [62] = 50,
  [63] = 48,
  [64] = 49,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 59,
  [69] = 54,
  [70] = 56,
  [71] = 57,
  [72] = 58,
  [73] = 55,
  [74] = 74,
  [75] = 74,
  [76] = 76,
  [77] = 77,
  [78] = 76,
  [79] = 79,
  [80] = 80,
  [81] = 80,
  [82] = 82,
  [83] = 83,
  [84] = 83,
  [85] = 85,
  [86] = 85,
  [87] = 87,
  [88] = 88,
  [89] = 87,
  [90] = 90,
  [91] = 91,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '!', 2,
        '"', 1,
        '#', 42,
        '%', 38,
        '(', 19,
        ')', 20,
        '*', 36,
        '+', 34,
        ',', 16,
        '-', 35,
        '.', 11,
        '/', 37,
        ';', 15,
        '<', 30,
        '=', 3,
        '>', 33,
        '{', 17,
        '}', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(29);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(27);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 11:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 13:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '!', 2,
        '"', 1,
        '#', 40,
        '%', 38,
        '(', 19,
        ')', 20,
        '*', 36,
        '+', 34,
        ',', 16,
        '-', 35,
        '.', 11,
        '/', 37,
        ';', 15,
        '<', 30,
        '=', 3,
        '>', 33,
        '{', 17,
        '}', 18,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PLUS_LT_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DASH_LT_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_STAR_LT_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SLASH_LT_GT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_STAR_STAR_LT_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PERCENT_LT_GT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '<') ADVANCE(6);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '<') ADVANCE(7);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '*') ADVANCE(39);
      if (lookahead == '<') ADVANCE(5);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '<') ADVANCE(8);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      if (lookahead == '<') ADVANCE(4);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_STAR_STAR);
      if (lookahead == '<') ADVANCE(9);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_line_comment_token2);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_line_comment_token2);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_line_comment_token3);
      if (lookahead == '#') ADVANCE(42);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_line_comment_token3);
      if (lookahead == '#') ADVANCE(47);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_line_comment_token3);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(50);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'i') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (lookahead == 'o') ADVANCE(4);
      if (lookahead == 'w') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'l') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'f') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'h') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_out);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 13},
  [2] = {.lex_state = 13},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 13},
  [5] = {.lex_state = 13},
  [6] = {.lex_state = 13},
  [7] = {.lex_state = 13},
  [8] = {.lex_state = 13},
  [9] = {.lex_state = 13},
  [10] = {.lex_state = 13},
  [11] = {.lex_state = 13},
  [12] = {.lex_state = 13},
  [13] = {.lex_state = 13},
  [14] = {.lex_state = 13},
  [15] = {.lex_state = 13},
  [16] = {.lex_state = 13},
  [17] = {.lex_state = 13},
  [18] = {.lex_state = 13},
  [19] = {.lex_state = 13},
  [20] = {.lex_state = 13},
  [21] = {.lex_state = 13},
  [22] = {.lex_state = 13},
  [23] = {.lex_state = 13},
  [24] = {.lex_state = 13},
  [25] = {.lex_state = 13},
  [26] = {.lex_state = 13},
  [27] = {.lex_state = 13},
  [28] = {.lex_state = 13},
  [29] = {.lex_state = 13},
  [30] = {.lex_state = 13},
  [31] = {.lex_state = 13},
  [32] = {.lex_state = 13},
  [33] = {.lex_state = 13},
  [34] = {.lex_state = 13},
  [35] = {.lex_state = 13},
  [36] = {.lex_state = 13},
  [37] = {.lex_state = 13},
  [38] = {.lex_state = 13},
  [39] = {.lex_state = 13},
  [40] = {.lex_state = 13},
  [41] = {.lex_state = 13},
  [42] = {.lex_state = 13},
  [43] = {.lex_state = 13},
  [44] = {.lex_state = 13},
  [45] = {.lex_state = 13},
  [46] = {.lex_state = 13},
  [47] = {.lex_state = 13},
  [48] = {.lex_state = 13},
  [49] = {.lex_state = 13},
  [50] = {.lex_state = 13},
  [51] = {.lex_state = 13},
  [52] = {.lex_state = 13},
  [53] = {.lex_state = 13},
  [54] = {.lex_state = 13},
  [55] = {.lex_state = 13},
  [56] = {.lex_state = 13},
  [57] = {.lex_state = 13},
  [58] = {.lex_state = 13},
  [59] = {.lex_state = 13},
  [60] = {.lex_state = 13},
  [61] = {.lex_state = 13},
  [62] = {.lex_state = 13},
  [63] = {.lex_state = 13},
  [64] = {.lex_state = 13},
  [65] = {.lex_state = 13},
  [66] = {.lex_state = 13},
  [67] = {.lex_state = 13},
  [68] = {.lex_state = 13},
  [69] = {.lex_state = 13},
  [70] = {.lex_state = 13},
  [71] = {.lex_state = 13},
  [72] = {.lex_state = 13},
  [73] = {.lex_state = 13},
  [74] = {.lex_state = 13},
  [75] = {.lex_state = 13},
  [76] = {.lex_state = 13},
  [77] = {.lex_state = 13},
  [78] = {.lex_state = 13},
  [79] = {.lex_state = 45},
  [80] = {.lex_state = 13},
  [81] = {.lex_state = 13},
  [82] = {.lex_state = 43},
  [83] = {.lex_state = 13},
  [84] = {.lex_state = 13},
  [85] = {.lex_state = 13},
  [86] = {.lex_state = 13},
  [87] = {.lex_state = 13},
  [88] = {.lex_state = 13},
  [89] = {.lex_state = 13},
  [90] = {(TSStateId)(-1)},
  [91] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_line_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_out] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT_GT] = ACTIONS(1),
    [anon_sym_PLUS_LT_GT] = ACTIONS(1),
    [anon_sym_DASH_LT_GT] = ACTIONS(1),
    [anon_sym_STAR_LT_GT] = ACTIONS(1),
    [anon_sym_SLASH_LT_GT] = ACTIONS(1),
    [anon_sym_STAR_STAR_LT_GT] = ACTIONS(1),
    [anon_sym_PERCENT_LT_GT] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_STAR_STAR] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
    [aux_sym_line_comment_token1] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(88),
    [sym__root_statement] = STATE(66),
    [sym_let_binding] = STATE(67),
    [sym_out_statement] = STATE(67),
    [sym_block] = STATE(67),
    [sym_if_expr] = STATE(67),
    [sym_while_expr] = STATE(67),
    [sym_line_comment] = STATE(1),
    [aux_sym_program_repeat1] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_out] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_if] = ACTIONS(13),
    [anon_sym_while] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
  },
  [2] = {
    [sym_line_comment] = STATE(2),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_let] = ACTIONS(19),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_out] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_while] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LT_GT] = ACTIONS(23),
    [anon_sym_PLUS_LT_GT] = ACTIONS(23),
    [anon_sym_DASH_LT_GT] = ACTIONS(23),
    [anon_sym_STAR_LT_GT] = ACTIONS(23),
    [anon_sym_SLASH_LT_GT] = ACTIONS(23),
    [anon_sym_STAR_STAR_LT_GT] = ACTIONS(23),
    [anon_sym_PERCENT_LT_GT] = ACTIONS(23),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(19),
    [anon_sym_SLASH] = ACTIONS(19),
    [anon_sym_PERCENT] = ACTIONS(19),
    [anon_sym_STAR_STAR] = ACTIONS(19),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_number_literal] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(21),
  },
  [3] = {
    [sym_line_comment] = STATE(3),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_let] = ACTIONS(19),
    [anon_sym_SEMI] = ACTIONS(21),
    [anon_sym_out] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_if] = ACTIONS(19),
    [anon_sym_while] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LT_GT] = ACTIONS(25),
    [anon_sym_PLUS_LT_GT] = ACTIONS(25),
    [anon_sym_DASH_LT_GT] = ACTIONS(25),
    [anon_sym_STAR_LT_GT] = ACTIONS(25),
    [anon_sym_SLASH_LT_GT] = ACTIONS(25),
    [anon_sym_STAR_STAR_LT_GT] = ACTIONS(25),
    [anon_sym_PERCENT_LT_GT] = ACTIONS(25),
    [anon_sym_BANG_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(19),
    [anon_sym_PLUS] = ACTIONS(19),
    [anon_sym_DASH] = ACTIONS(19),
    [anon_sym_STAR] = ACTIONS(19),
    [anon_sym_SLASH] = ACTIONS(19),
    [anon_sym_PERCENT] = ACTIONS(19),
    [anon_sym_STAR_STAR] = ACTIONS(19),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_number_literal] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(21),
  },
  [4] = {
    [sym_line_comment] = STATE(4),
    [sym_identifier] = ACTIONS(27),
    [anon_sym_let] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(29),
    [anon_sym_out] = ACTIONS(27),
    [anon_sym_COMMA] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_if] = ACTIONS(27),
    [anon_sym_while] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_LT_GT] = ACTIONS(29),
    [anon_sym_PLUS_LT_GT] = ACTIONS(29),
    [anon_sym_DASH_LT_GT] = ACTIONS(29),
    [anon_sym_STAR_LT_GT] = ACTIONS(29),
    [anon_sym_SLASH_LT_GT] = ACTIONS(29),
    [anon_sym_STAR_STAR_LT_GT] = ACTIONS(29),
    [anon_sym_PERCENT_LT_GT] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(29),
    [anon_sym_EQ_EQ] = ACTIONS(29),
    [anon_sym_LT] = ACTIONS(27),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_STAR_STAR] = ACTIONS(27),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_number_literal] = ACTIONS(29),
    [sym_string_literal] = ACTIONS(29),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(5), 1,
      sym_line_comment,
    ACTIONS(31), 8,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_STAR,
      sym_identifier,
    ACTIONS(33), 17,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      sym_number_literal,
      sym_string_literal,
  [36] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(6), 1,
      sym_line_comment,
    ACTIONS(35), 8,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_STAR,
      sym_identifier,
    ACTIONS(37), 17,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      sym_number_literal,
      sym_string_literal,
  [72] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(7), 1,
      sym_line_comment,
    ACTIONS(19), 8,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_STAR,
      sym_identifier,
    ACTIONS(21), 17,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_STAR_STAR,
      sym_number_literal,
      sym_string_literal,
  [108] = 8,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    STATE(8), 1,
      sym_line_comment,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(39), 7,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(41), 12,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_number_literal,
      sym_string_literal,
  [152] = 11,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    STATE(9), 1,
      sym_line_comment,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(51), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
    ACTIONS(53), 8,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_number_literal,
      sym_string_literal,
  [202] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    STATE(10), 1,
      sym_line_comment,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(39), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
    ACTIONS(41), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      sym_number_literal,
      sym_string_literal,
  [250] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    STATE(11), 1,
      sym_line_comment,
    ACTIONS(39), 8,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_STAR,
      sym_identifier,
    ACTIONS(41), 16,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      sym_number_literal,
      sym_string_literal,
  [288] = 7,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    STATE(12), 1,
      sym_line_comment,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(39), 7,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
    ACTIONS(41), 14,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_number_literal,
      sym_string_literal,
  [330] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    STATE(13), 1,
      sym_line_comment,
    ACTIONS(39), 8,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_STAR,
      sym_identifier,
    ACTIONS(41), 16,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      sym_number_literal,
      sym_string_literal,
  [368] = 12,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    ACTIONS(63), 1,
      anon_sym_SEMI,
    STATE(14), 1,
      sym_line_comment,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(65), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(61), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [417] = 18,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      anon_sym_let,
    ACTIONS(71), 1,
      anon_sym_out,
    ACTIONS(73), 1,
      anon_sym_RBRACE,
    ACTIONS(75), 1,
      anon_sym_if,
    ACTIONS(77), 1,
      anon_sym_while,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(14), 1,
      sym__expression,
    STATE(15), 1,
      sym_line_comment,
    STATE(17), 1,
      aux_sym_block_repeat1,
    STATE(53), 1,
      sym__items,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(52), 4,
      sym_let_binding,
      sym_out_statement,
      sym_if_expr,
      sym_while_expr,
  [478] = 18,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      anon_sym_let,
    ACTIONS(71), 1,
      anon_sym_out,
    ACTIONS(75), 1,
      anon_sym_if,
    ACTIONS(77), 1,
      anon_sym_while,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(14), 1,
      sym__expression,
    STATE(15), 1,
      aux_sym_block_repeat1,
    STATE(16), 1,
      sym_line_comment,
    STATE(53), 1,
      sym__items,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(52), 4,
      sym_let_binding,
      sym_out_statement,
      sym_if_expr,
      sym_while_expr,
  [539] = 17,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(85), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_let,
    ACTIONS(91), 1,
      anon_sym_out,
    ACTIONS(94), 1,
      anon_sym_RBRACE,
    ACTIONS(96), 1,
      anon_sym_if,
    ACTIONS(99), 1,
      anon_sym_while,
    ACTIONS(102), 1,
      anon_sym_LPAREN,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(14), 1,
      sym__expression,
    STATE(53), 1,
      sym__items,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(105), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(17), 2,
      sym_line_comment,
      aux_sym_block_repeat1,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(52), 4,
      sym_let_binding,
      sym_out_statement,
      sym_if_expr,
      sym_while_expr,
  [598] = 18,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      anon_sym_let,
    ACTIONS(71), 1,
      anon_sym_out,
    ACTIONS(75), 1,
      anon_sym_if,
    ACTIONS(77), 1,
      anon_sym_while,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(14), 1,
      sym__expression,
    STATE(17), 1,
      aux_sym_block_repeat1,
    STATE(18), 1,
      sym_line_comment,
    STATE(53), 1,
      sym__items,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(52), 4,
      sym_let_binding,
      sym_out_statement,
      sym_if_expr,
      sym_while_expr,
  [659] = 18,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(67), 1,
      sym_identifier,
    ACTIONS(69), 1,
      anon_sym_let,
    ACTIONS(71), 1,
      anon_sym_out,
    ACTIONS(75), 1,
      anon_sym_if,
    ACTIONS(77), 1,
      anon_sym_while,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(110), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(14), 1,
      sym__expression,
    STATE(18), 1,
      aux_sym_block_repeat1,
    STATE(19), 1,
      sym_line_comment,
    STATE(53), 1,
      sym__items,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
    STATE(52), 4,
      sym_let_binding,
      sym_out_statement,
      sym_if_expr,
      sym_while_expr,
  [720] = 12,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    ACTIONS(112), 1,
      anon_sym_SEMI,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    STATE(20), 1,
      sym_line_comment,
    STATE(78), 1,
      aux_sym_out_statement_repeat1,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [762] = 12,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(116), 1,
      anon_sym_SEMI,
    STATE(21), 1,
      sym_line_comment,
    STATE(76), 1,
      aux_sym_out_statement_repeat1,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [804] = 11,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    STATE(22), 1,
      sym_line_comment,
    STATE(63), 1,
      sym_block,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [843] = 11,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    STATE(23), 1,
      sym_line_comment,
    STATE(68), 1,
      sym_block,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [882] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    STATE(24), 1,
      sym_line_comment,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(118), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [919] = 11,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    STATE(25), 1,
      sym_line_comment,
    STATE(48), 1,
      sym_block,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [958] = 11,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_line_comment,
    STATE(59), 1,
      sym_block,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [997] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    ACTIONS(122), 1,
      anon_sym_RPAREN,
    STATE(27), 1,
      sym_line_comment,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1033] = 11,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_out,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(15), 1,
      anon_sym_while,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    STATE(28), 1,
      sym_line_comment,
    STATE(29), 1,
      aux_sym_program_repeat1,
    STATE(66), 1,
      sym__root_statement,
    STATE(67), 5,
      sym_let_binding,
      sym_out_statement,
      sym_block,
      sym_if_expr,
      sym_while_expr,
  [1071] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(126), 1,
      ts_builtin_sym_end,
    ACTIONS(128), 1,
      anon_sym_let,
    ACTIONS(131), 1,
      anon_sym_out,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    ACTIONS(137), 1,
      anon_sym_if,
    ACTIONS(140), 1,
      anon_sym_while,
    STATE(66), 1,
      sym__root_statement,
    STATE(29), 2,
      sym_line_comment,
      aux_sym_program_repeat1,
    STATE(67), 5,
      sym_let_binding,
      sym_out_statement,
      sym_block,
      sym_if_expr,
      sym_while_expr,
  [1107] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(45), 1,
      anon_sym_STAR,
    ACTIONS(49), 1,
      anon_sym_STAR_STAR,
    ACTIONS(143), 1,
      anon_sym_SEMI,
    STATE(30), 1,
      sym_line_comment,
    ACTIONS(43), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(47), 2,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(55), 2,
      anon_sym_BANG_EQ,
      anon_sym_EQ_EQ,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1143] = 11,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(147), 1,
      anon_sym_SEMI,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(21), 1,
      sym__expression,
    STATE(31), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1180] = 11,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    ACTIONS(149), 1,
      anon_sym_SEMI,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(20), 1,
      sym__expression,
    STATE(32), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1217] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(23), 1,
      sym__expression,
    STATE(33), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1251] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(26), 1,
      sym__expression,
    STATE(34), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1285] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(27), 1,
      sym__expression,
    STATE(35), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1319] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(9), 1,
      sym__expression,
    STATE(36), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1353] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(11), 1,
      sym__expression,
    STATE(37), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1387] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(10), 1,
      sym__expression,
    STATE(38), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1421] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(8), 1,
      sym__expression,
    STATE(39), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1455] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(12), 1,
      sym__expression,
    STATE(40), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1489] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(22), 1,
      sym__expression,
    STATE(41), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1523] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(13), 1,
      sym__expression,
    STATE(42), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1557] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(24), 1,
      sym__expression,
    STATE(43), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1591] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(153), 1,
      anon_sym_SEMI,
    STATE(44), 1,
      sym_line_comment,
    ACTIONS(155), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(151), 6,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      sym_identifier,
  [1615] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(159), 1,
      anon_sym_SEMI,
    STATE(45), 1,
      sym_line_comment,
    ACTIONS(161), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(157), 6,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      sym_identifier,
  [1639] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(30), 1,
      sym__expression,
    STATE(46), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1673] = 10,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(145), 1,
      sym_identifier,
    STATE(3), 1,
      sym_parenthesized_expression,
    STATE(7), 1,
      sym__literal,
    STATE(25), 1,
      sym__expression,
    STATE(47), 1,
      sym_line_comment,
    STATE(65), 1,
      sym__lhs_expression,
    ACTIONS(81), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(6), 3,
      sym_assignment_expression,
      sym_binary_expression,
      sym_primary_expression,
  [1707] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(167), 1,
      anon_sym_else,
    STATE(48), 1,
      sym_line_comment,
    ACTIONS(165), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(163), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1730] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(49), 1,
      sym_line_comment,
    ACTIONS(171), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(169), 6,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      sym_identifier,
  [1751] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(50), 1,
      sym_line_comment,
    ACTIONS(161), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(157), 6,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      sym_identifier,
  [1772] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(51), 1,
      sym_line_comment,
    ACTIONS(175), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(173), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1792] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(52), 1,
      sym_line_comment,
    ACTIONS(65), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(61), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1812] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(53), 1,
      sym_line_comment,
    ACTIONS(179), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(177), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1832] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(54), 1,
      sym_line_comment,
    ACTIONS(183), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(181), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1852] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(55), 1,
      sym_line_comment,
    ACTIONS(187), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(185), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1872] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(56), 1,
      sym_line_comment,
    ACTIONS(191), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(189), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1892] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(57), 1,
      sym_line_comment,
    ACTIONS(195), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(193), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1912] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(58), 1,
      sym_line_comment,
    ACTIONS(199), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(197), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1932] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(59), 1,
      sym_line_comment,
    ACTIONS(203), 4,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(201), 5,
      anon_sym_let,
      anon_sym_out,
      anon_sym_if,
      anon_sym_while,
      sym_identifier,
  [1952] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(205), 1,
      anon_sym_SEMI,
    STATE(60), 1,
      sym_line_comment,
    ACTIONS(155), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
  [1971] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(207), 1,
      anon_sym_SEMI,
    STATE(61), 1,
      sym_line_comment,
    ACTIONS(161), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
  [1990] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(62), 1,
      sym_line_comment,
    ACTIONS(161), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
  [2006] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(209), 1,
      anon_sym_else,
    STATE(63), 1,
      sym_line_comment,
    ACTIONS(165), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_while,
  [2024] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(64), 1,
      sym_line_comment,
    ACTIONS(171), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
  [2040] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(65), 1,
      sym_line_comment,
    ACTIONS(25), 7,
      anon_sym_LT_GT,
      anon_sym_PLUS_LT_GT,
      anon_sym_DASH_LT_GT,
      anon_sym_STAR_LT_GT,
      anon_sym_SLASH_LT_GT,
      anon_sym_STAR_STAR_LT_GT,
      anon_sym_PERCENT_LT_GT,
  [2056] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(66), 1,
      sym_line_comment,
    ACTIONS(211), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_while,
  [2071] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(67), 1,
      sym_line_comment,
    ACTIONS(213), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_while,
  [2086] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(68), 1,
      sym_line_comment,
    ACTIONS(203), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_while,
  [2101] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(69), 1,
      sym_line_comment,
    ACTIONS(183), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_while,
  [2116] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(70), 1,
      sym_line_comment,
    ACTIONS(191), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_while,
  [2131] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(71), 1,
      sym_line_comment,
    ACTIONS(195), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_while,
  [2146] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(72), 1,
      sym_line_comment,
    ACTIONS(199), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_while,
  [2161] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(73), 1,
      sym_line_comment,
    ACTIONS(187), 6,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_out,
      anon_sym_LBRACE,
      anon_sym_if,
      anon_sym_while,
  [2176] = 5,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_POUND,
    STATE(74), 1,
      sym_line_comment,
    STATE(71), 2,
      sym_block,
      sym_if_expr,
  [2193] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    ACTIONS(215), 1,
      anon_sym_if,
    STATE(75), 1,
      sym_line_comment,
    STATE(57), 2,
      sym_block,
      sym_if_expr,
  [2210] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(217), 1,
      anon_sym_SEMI,
    STATE(76), 1,
      sym_line_comment,
    STATE(77), 1,
      aux_sym_out_statement_repeat1,
  [2226] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(118), 1,
      anon_sym_SEMI,
    ACTIONS(219), 1,
      anon_sym_COMMA,
    STATE(77), 2,
      sym_line_comment,
      aux_sym_out_statement_repeat1,
  [2240] = 5,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(114), 1,
      anon_sym_COMMA,
    ACTIONS(222), 1,
      anon_sym_SEMI,
    STATE(77), 1,
      aux_sym_out_statement_repeat1,
    STATE(78), 1,
      sym_line_comment,
  [2256] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(224), 1,
      aux_sym_line_comment_token1,
    ACTIONS(226), 1,
      aux_sym_line_comment_token3,
    STATE(79), 1,
      sym_line_comment,
  [2269] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(228), 1,
      anon_sym_LT_GT,
    STATE(80), 1,
      sym_line_comment,
    STATE(84), 1,
      sym__initializer,
  [2282] = 4,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(228), 1,
      anon_sym_LT_GT,
    STATE(81), 1,
      sym_line_comment,
    STATE(83), 1,
      sym__initializer,
  [2295] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(230), 1,
      aux_sym_line_comment_token2,
    STATE(82), 1,
      sym_line_comment,
  [2305] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(232), 1,
      anon_sym_SEMI,
    STATE(83), 1,
      sym_line_comment,
  [2315] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(234), 1,
      anon_sym_SEMI,
    STATE(84), 1,
      sym_line_comment,
  [2325] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(236), 1,
      sym_string_literal,
    STATE(85), 1,
      sym_line_comment,
  [2335] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(238), 1,
      sym_string_literal,
    STATE(86), 1,
      sym_line_comment,
  [2345] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(240), 1,
      sym_identifier,
    STATE(87), 1,
      sym_line_comment,
  [2355] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
    STATE(88), 1,
      sym_line_comment,
  [2365] = 3,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(244), 1,
      sym_identifier,
    STATE(89), 1,
      sym_line_comment,
  [2375] = 1,
    ACTIONS(246), 1,
      ts_builtin_sym_end,
  [2379] = 1,
    ACTIONS(248), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 36,
  [SMALL_STATE(7)] = 72,
  [SMALL_STATE(8)] = 108,
  [SMALL_STATE(9)] = 152,
  [SMALL_STATE(10)] = 202,
  [SMALL_STATE(11)] = 250,
  [SMALL_STATE(12)] = 288,
  [SMALL_STATE(13)] = 330,
  [SMALL_STATE(14)] = 368,
  [SMALL_STATE(15)] = 417,
  [SMALL_STATE(16)] = 478,
  [SMALL_STATE(17)] = 539,
  [SMALL_STATE(18)] = 598,
  [SMALL_STATE(19)] = 659,
  [SMALL_STATE(20)] = 720,
  [SMALL_STATE(21)] = 762,
  [SMALL_STATE(22)] = 804,
  [SMALL_STATE(23)] = 843,
  [SMALL_STATE(24)] = 882,
  [SMALL_STATE(25)] = 919,
  [SMALL_STATE(26)] = 958,
  [SMALL_STATE(27)] = 997,
  [SMALL_STATE(28)] = 1033,
  [SMALL_STATE(29)] = 1071,
  [SMALL_STATE(30)] = 1107,
  [SMALL_STATE(31)] = 1143,
  [SMALL_STATE(32)] = 1180,
  [SMALL_STATE(33)] = 1217,
  [SMALL_STATE(34)] = 1251,
  [SMALL_STATE(35)] = 1285,
  [SMALL_STATE(36)] = 1319,
  [SMALL_STATE(37)] = 1353,
  [SMALL_STATE(38)] = 1387,
  [SMALL_STATE(39)] = 1421,
  [SMALL_STATE(40)] = 1455,
  [SMALL_STATE(41)] = 1489,
  [SMALL_STATE(42)] = 1523,
  [SMALL_STATE(43)] = 1557,
  [SMALL_STATE(44)] = 1591,
  [SMALL_STATE(45)] = 1615,
  [SMALL_STATE(46)] = 1639,
  [SMALL_STATE(47)] = 1673,
  [SMALL_STATE(48)] = 1707,
  [SMALL_STATE(49)] = 1730,
  [SMALL_STATE(50)] = 1751,
  [SMALL_STATE(51)] = 1772,
  [SMALL_STATE(52)] = 1792,
  [SMALL_STATE(53)] = 1812,
  [SMALL_STATE(54)] = 1832,
  [SMALL_STATE(55)] = 1852,
  [SMALL_STATE(56)] = 1872,
  [SMALL_STATE(57)] = 1892,
  [SMALL_STATE(58)] = 1912,
  [SMALL_STATE(59)] = 1932,
  [SMALL_STATE(60)] = 1952,
  [SMALL_STATE(61)] = 1971,
  [SMALL_STATE(62)] = 1990,
  [SMALL_STATE(63)] = 2006,
  [SMALL_STATE(64)] = 2024,
  [SMALL_STATE(65)] = 2040,
  [SMALL_STATE(66)] = 2056,
  [SMALL_STATE(67)] = 2071,
  [SMALL_STATE(68)] = 2086,
  [SMALL_STATE(69)] = 2101,
  [SMALL_STATE(70)] = 2116,
  [SMALL_STATE(71)] = 2131,
  [SMALL_STATE(72)] = 2146,
  [SMALL_STATE(73)] = 2161,
  [SMALL_STATE(74)] = 2176,
  [SMALL_STATE(75)] = 2193,
  [SMALL_STATE(76)] = 2210,
  [SMALL_STATE(77)] = 2226,
  [SMALL_STATE(78)] = 2240,
  [SMALL_STATE(79)] = 2256,
  [SMALL_STATE(80)] = 2269,
  [SMALL_STATE(81)] = 2282,
  [SMALL_STATE(82)] = 2295,
  [SMALL_STATE(83)] = 2305,
  [SMALL_STATE(84)] = 2315,
  [SMALL_STATE(85)] = 2325,
  [SMALL_STATE(86)] = 2335,
  [SMALL_STATE(87)] = 2345,
  [SMALL_STATE(88)] = 2355,
  [SMALL_STATE(89)] = 2365,
  [SMALL_STATE(90)] = 2375,
  [SMALL_STATE(91)] = 2379,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary_expression, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary_expression, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__lhs_expression, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__literal, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 6),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 6),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_expression, 3, 0, 5),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_expression, 3, 0, 5),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__items, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__items, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [88] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_out_statement_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__initializer, 2, 0, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expr, 3, 0, 2),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expr, 3, 0, 2),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__items, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__items, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out_statement, 3, 0, 1),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_statement, 3, 0, 1),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out_statement, 4, 0, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_statement, 4, 0, 1),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_out_statement, 5, 0, 1),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_out_statement, 5, 0, 1),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_expr, 5, 0, 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expr, 5, 0, 2),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_binding, 4, 0, 4),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_binding, 4, 0, 4),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_expr, 3, 0, 2),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_expr, 3, 0, 2),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_program_repeat1, 1, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__root_statement, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [219] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_out_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [242] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tes(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
